import math

# Various dimensions:
LIDAR_MEASUREMENT = 16*20
IMAGE_DIMENSIONS = IMAGE_WIDTH * IMAGE_HEIGHT
GOAL_DIR_DIMS = 3
GOAL_MAG_DIMS = 1
ATTITUDE_DIMS = 3
LIN_VELOCITY_DIMS = 3
ANG_VELOCITY_DIMS = 3
ACTION_DIMS = 4
TOTAL_IP_DIMS = (
    GOAL_DIR_DIMS
    + GOAL_MAG_DIMS
    + ATTITUDE_DIMS
    + LIN_VELOCITY_DIMS
    + ANG_VELOCITY_DIMS
    + ACTION_DIMS
    + LIDAR_MEASUREMENT
)

DIST_DIVIDER = 1.0

IMAGE_MAX_DEPTH = 10.0
IMAGE_MIN_DEPTH = 0.2


ODOM_TOPIC = "/mavros/local_position/odom_in_map"
ACTION_PUB_TOPIC = "/cmd_vel"
MAVROS_STATE_TOPIC = "/mavros/state"
TARGET_TOPIC = "/target"
USE_MAVROS_STATE = True
IMAGE_TOPIC = "/d455/depth/image_rect_raw_throttled"

GOAL_DIR_TOPIC_NAME = "/goal_dir"
SPEED_MAGNITUDE = 1.5
USE_FILTERED_ACTIONS = True
SAMPLE_FROM_LATENT = False
ACTION_FILTER_BETA = 0.8
device = "cuda:0"
